import { StyleSheet } from 'react-native';

import { theme } from '@assets/theme';

export const FRAME_SIZE = 280;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  safeArea: {
    flex: 1,
  },
  cameraWrapper: {
    flex: 1,
    position: 'relative',
  },
  imageBackground: {
    flex: 1,
    borderRadius: 0,
    overflow: 'hidden',
    backgroundColor: '#0f172a',
    position: 'relative',
  },
  cameraFeed: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
  },
  placeholderContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  capturedImage: {
    width: '100%',
    height: '100%',
    opacity: 0.92,
  },
  overlayGradient: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  header: {
    position: 'absolute',
    top: theme.spacing.lg,
    left: theme.spacing.md,
    right: theme.spacing.md,
    flexDirection: 'row',
    justifyContent: 'space-between',
    zIndex: 2,
  },
  headerButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
  },
  scanArea: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scanContent: {
    width: FRAME_SIZE,
    height: FRAME_SIZE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scanFrame: {
    color: '#0EA5E9',
  },
  placeholderInsideFrame: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  placeholderText: {
    color: theme.colors.subText_2,
    textAlign: 'center',
    fontSize: theme.fonts.size.md,
  },
  scanLine: {
    position: 'absolute',
    top: 0,
    left: '10%',
    right: '10%',
    height: 2,
    backgroundColor: '#0EA5E9',
    shadowColor: '#0EA5E9',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 10,
  },
  promptWrapper: {
    marginTop: theme.spacing.lg,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 20,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  promptText: {
    color: theme.colors.white,
    fontSize: theme.fonts.size.sm,
    fontWeight: theme.fonts.weight.semibold,
  },
  controls: {
    position: 'absolute',
    bottom: theme.spacing.xl,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  smallButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(255,255,255,0.12)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  captureButton: {
    width: 90,
    height: 90,
    borderRadius: 45,
    borderWidth: 4,
    borderColor: theme.colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  captureDisabled: {
    opacity: 0.5,
  },
  captureInner: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: theme.colors.white,
  },
  resultSheet: {
    backgroundColor: theme.colors.white,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingHorizontal: theme.spacing.lg,
    paddingTop: theme.spacing.lg,
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 10,
  },
  dragHandle: {
    width: 56,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#e5e7eb',
    alignSelf: 'center',
    marginBottom: theme.spacing.md,
  },
  sheetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: theme.spacing.md,
  },
  resultTitle: {
    fontSize: theme.fonts.size.xl,
    fontWeight: theme.fonts.weight.bold,
    color: theme.colors.text,
    marginBottom: theme.spacing.xs,
  },
  badge: {
    alignSelf: 'flex-start',
    backgroundColor: '#f3f4f6',
    borderRadius: 8,
    paddingHorizontal: theme.spacing.xs,
    paddingVertical: theme.spacing.xs,
  },
  badgeText: {
    fontSize: theme.fonts.size.xs,
    color: theme.colors.subText_2,
    fontWeight: theme.fonts.weight.bold,
    textTransform: 'uppercase',
  },
  closeButton: {
    padding: theme.spacing.xs,
    borderRadius: 999,
    backgroundColor: '#f3f4f6',
  },
  calorieRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginBottom: theme.spacing.lg,
  },
  calorieValue: {
    fontSize: 56,
    fontWeight: theme.fonts.weight.bold,
    color: '#0EA5E9',
  },
  calorieUnit: {
    marginLeft: theme.spacing.xs,
    fontSize: theme.fonts.size.lg,
    fontWeight: theme.fonts.weight.semibold,
    color: theme.colors.subText_2,
  },
  macroRow: {
    flexDirection: 'row',
    gap: theme.spacing.sm,
    marginBottom: theme.spacing.lg,
  },
  macroItem: {
    flex: 1,
    backgroundColor: '#f8fafc',
    padding: theme.spacing.sm,
    borderRadius: theme.spacing.md,
  },
  macroLabel: {
    fontSize: theme.fonts.size.xs,
    color: theme.colors.subText_2,
    marginBottom: theme.spacing.xs,
  },
  macroValue: {
    fontSize: theme.fonts.size.md,
    fontWeight: theme.fonts.weight.bold,
    color: theme.colors.text,
    marginBottom: theme.spacing.xs,
  },
  macroTrack: {
    height: 6,
    borderRadius: 6,
    backgroundColor: '#e5e7eb',
    overflow: 'hidden',
  },
  macroFill: {
    height: '100%',
    borderRadius: 6,
  },
  insightBox: {
    flexDirection: 'row',
    backgroundColor: '#E0F2FE',
    borderRadius: theme.spacing.md,
    padding: theme.spacing.md,
    marginBottom: theme.spacing.lg,
    alignItems: 'flex-start',
  },
  insightIcon: {
    marginRight: theme.spacing.sm,
  },
  insightTextWrapper: {
    flex: 1,
  },
  insightTitle: {
    color: '#0C4A6E',
    fontWeight: theme.fonts.weight.bold,
    fontSize: theme.fonts.size.sm,
    marginBottom: theme.spacing.xs,
  },
  insightBody: {
    color: '#334155',
    fontSize: theme.fonts.size.sm,
    lineHeight: theme.spacing.lg,
  },
  addButton: {
    width: '100%',
    backgroundColor: '#0EA5E9',
    borderRadius: theme.spacing.md,
    paddingVertical: theme.spacing.lg,
    alignItems: 'center',
    shadowColor: '#0EA5E9',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 6,
  },
  addButtonText: {
    color: theme.colors.white,
    fontWeight: theme.fonts.weight.bold,
    fontSize: theme.fonts.size.md,
  },
});
